<?php

namespace Qihoo\ToolBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SzSearchTotalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SzSearchTotalRepository extends EntityRepository
{
	public function getQuery($page, $pageSize, $params = array())
    {
        $page = intval($page);
        $pageSize = intval($pageSize);
        $em = $this->getEntityManager();
        $where = array();
        $sql = 'select * from sz_search_total where day >= \''.$params['begin'].'\' and day <= \''.$params['end']
        .'\' order by day desc limit '. ($page-1)*$pageSize.", $pageSize";
        $totalSql = 'select count(*) as total from sz_search_total where day >= \''.$params['begin'].'\' and day <= \''.$params['end'].'\'';
        $conn = $em->getConnection();
        $retTotal = $conn->fetchAssoc($totalSql);
        $ret = $conn->fetchAll($sql);
        $conn->close();
        return array($retTotal['total'], $ret);
    }
}
